[build]
  publish = "dist/"
  command = "sed -i \"s|ALLOWED_URL|${SITE_URL}|g\" netlify.toml && yarn && node --unhandled-rejections=strict generate.js"
  functions = "functions"
[context.production]
  environment = { SITE_URL = "https://alpha.audioxide.com", API_URL = "https://alpha.audioxide.com/api" }
[context.beta]
  environment = { SITE_URL = "https://beta.audioxide.com", API_URL = "https://beta.audioxide.com/api" }
[context.alpha]
  environment = { SITE_URL = "https://alpha.audioxide.com", API_URL = "https://alpha.audioxide.com/api" }

[[redirects]]
  from = "/search"
  to = "/.netlify/functions/search"
  query = {term = ":term"}
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "ALLOWED_URL"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json; charset=UTF-8"
    Vary = "Origin"

[[headers]]
  for = "/**/*.json"
  [headers.values]
    Content-Type = "application/json; charset=UTF-8"
    Vary = "Origin"

[[headers]]
  for = "/feed/*"
  [headers.values]
    Content-Type = "application/rss+xml; charset=UTF-8"
    Vary = "Origin"

[[headers]]
  for = "/images/**/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"
    Vary = "Origin"

[[headers]]
  for = "/images/**/*.png"
  [headers.values]
    Content-Type = "image/png"
    Vary = "Origin"
