[build]
  publish = "dist/"
  command = "sed -i \"s|ALLOWED_URL|${SITE_URL}|g\" netlify.toml && yarn && yarn build"
  functions = "functions"
  environment = { SITE_URL = "https://audioxide.com", API_URL = "https://api.audioxide.com" }

[[plugins]]
package = "/plugins/netlify-plugin-cache-audioxide-data"

[[plugins]]
package = "/plugins/netlify-plugin-trigger-website-rebuild"

[[redirects]]
  from = "/search"
  to = "/.netlify/functions/search"
  query = {term = ":term"}
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "ALLOWED_URL"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json; charset=UTF-8"
    Vary = "Origin"

[[headers]]
  for = "/**/*.json"
  [headers.values]
    Content-Type = "application/json; charset=UTF-8"
    Vary = "Origin"

[[headers]]
  for = "/feed/*"
  [headers.values]
    Content-Type = "application/rss+xml; charset=UTF-8"
    Vary = "Origin"

[[headers]]
  for = "/images/**/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"
    Vary = "Origin"

[[headers]]
  for = "/images/**/*.png"
  [headers.values]
    Content-Type = "image/png"
    Vary = "Origin"
