[build]
  publish = "dist/"
  command = "sed -i \"s|ALLOWED_URL|${SITE_URL}|g\" netlify.toml && yarn && node --unhandled-rejections=strict generate.js"
[context.production]
  environment = { SITE_URL = "https://alpha.audioxide.com", API_URL = "https://alpha.audioxide.com/api" }
[context.beta]
  environment = { SITE_URL = "https://beta.audioxide.com", API_URL = "https://beta.audioxide.com/api" }
[context.alpha]
  environment = { SITE_URL = "https://alpha.audioxide.com", API_URL = "https://alpha.audioxide.com/api" }

[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "ALLOWED_URL"
    Vary = "Origin"

[[headers]]
  for = "/feed/*.html"
  [headers.values]
    Content-Type = "application/rss+xml; charset=UTF-8"

[[headers]]
  for = "/images/**/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/images/**/*.png"
  [headers.values]
    Content-Type = "image/png"
